/**
 * Two-canary test for the interpreter-fallback detector.
 *
 * A detector that passes on a healthy build proves nothing on its own. Both
 * canaries here go through parseman's REAL macro transform — `transformMacro`
 * is the exact function the rolldown plugin calls per module, and the point at
 * which fallback-vs-compiled is decided — so the fallback side is a real
 * fallback, not a hand-written imitation of one.
 *
 * The pair also pins the two facts the old detectors got wrong:
 *   - the fallback artifact is SMALLER (measured ~91% smaller here), which is
 *     the false-win hazard stated in GRAMMAR-SIZE-FACTS §2.7;
 *   - `_rp[N].parse(`, which `check:macro` scanned for, is absent from BOTH
 *     sides, so it never had any power to catch this.
 */
import { strict as assert } from 'node:assert';
import { test } from 'node:test';
import { transformMacro } from 'parseman/plugin';
import {
  RUNTIME_DRIVERS,
  TABLE_DRIVER_SPECIFIER,
  artifactFallbacks,
  scanBuildLog
} from '../parseman-fallback-detector.mjs';

const MACRO_IMPORT = `import { rules, sequence, literal, many } from 'parseman' with { type: 'macro' };`;

/** Compiles fully: every argument is statically evaluable. */
const HEALTHY_SOURCE = `
${MACRO_IMPORT}
export const g = rules(_g => ({
  Main: sequence(literal('a'), many(literal('b')))
}));
`;

/**
 * Falls back: `literal()` closes over a value the build-time evaluator cannot
 * resolve. parseman's `docs/guide/macro-mode.md` states this is left as-is, and
 * `src/plugin/evaluator.ts` returns null for external variables. The test does
 * not take that on trust — it asserts the fallback actually happened before
 * asserting the detector caught it.
 */
const FALLBACK_SOURCE = `
${MACRO_IMPORT}
const runtimeValue = globalThis.SOME_RUNTIME_THING;
export const g = rules(_g => ({
  Main: sequence(literal(runtimeValue), many(literal('b')))
}));
`;

function transform(source, id) {
  const result = transformMacro(source, id);
  assert.notEqual(result, null, `transformMacro returned null for ${id} — the module was not processed at all`);
  return result;
}

const healthy = transform(HEALTHY_SOURCE, '/canary/healthy.ts');
const fallback = transform(FALLBACK_SOURCE, '/canary/fallback.ts');

test('the fallback canary really is a fallback', () => {
  assert.equal(healthy.warnings.length, 0, `healthy canary warned: ${healthy.warnings.join(' | ')}`);
  assert.equal(fallback.warnings.length, 1);
  assert.match(fallback.warnings[0], /running via the interpreter/);

  /*
   * Compiled output carries parseman's provenance banner; a fully fallen-back
   * module is emitted untouched and has none.
   */
  assert.match(healthy.code, /Generated by parseman v/);
  assert.doesNotMatch(fallback.code, /Generated by parseman v/);
});

test('the fallback produces a SMALLER artifact — the false win', () => {
  assert.ok(
    fallback.code.length < healthy.code.length / 2,
    `expected the fallback to be dramatically smaller; got fallback=${fallback.code.length}B `
    + `healthy=${healthy.code.length}B`
  );
});

test('the retired `_rp[N].parse(` marker fires on NEITHER side', () => {
  const marker = /_rp\[\d+\]\.parse\(/;
  assert.doesNotMatch(healthy.code, marker);

  /*
   * The load-bearing assertion. `check:macro` treated a zero count here as
   * proof of full compilation for as long as it existed. If parseman ever does
   * emit `_rp` from the macro this flips, and the comment in
   * check-macro-buildable.mjs explaining why the marker was dropped is wrong.
   */
  assert.doesNotMatch(fallback.code, marker);
});

test('the artifact detector PASSES the healthy canary', () => {
  assert.deepEqual(artifactFallbacks(healthy.code), []);
});

test('the artifact detector FAILS the fallback canary', () => {
  const findings = artifactFallbacks(fallback.code);
  assert.ok(findings.length > 0, 'the detector cleared a module that fell back to the interpreter');
  assert.ok(findings.every(f => f.kind === 'combinator'));
  const names = findings.map(f => f.detail);
  for (const combinator of ['rules', 'sequence', 'literal', 'many']) {
    assert.ok(
      names.some(detail => detail.includes(`imports '${combinator}'`)),
      `expected the surviving combinator '${combinator}' to be reported`
    );
  }
});

test('the build-log detector FAILS the fallback canary and passes the healthy one', () => {
  assert.deepEqual(scanBuildLog(healthy.warnings.join('\n')), []);
  assert.equal(scanBuildLog(fallback.warnings.join('\n')).length, 1);
});

test('a runtime driver import is not mistaken for a fallback', () => {
  /*
   * The shape every parser package really ships — read off
   * `css-parser/lib/cst-host.js` and each parser's `lib/chunks/parse-with.js`.
   * Widening the old `grep 'from "parseman"'` detector past `lib/grammar/`
   * reddened exactly these, which is why it had to stay narrow.
   */
  const driverModule = 'import { cstBuildHost, parseDoc, run, buildLineIndex, offsetToLineCol } from "parseman";\nexport const x = run;';
  assert.deepEqual(artifactFallbacks(driverModule), []);
  for (const driver of ['cstBuildHost', 'parseDoc', 'run', 'buildLineIndex', 'offsetToLineCol']) {
    assert.ok(RUNTIME_DRIVERS.has(driver));
  }
});

test('a namespace import is a finding — it reaches the whole vocabulary', () => {
  const findings = artifactFallbacks('import * as pm from "parseman";\nexport const g = pm.rules(_g => ({}));');
  assert.equal(findings.length, 1);
  assert.equal(findings[0].kind, 'combinator');
});

test('the table lowering trips loudly instead of silently passing', () => {
  /*
   * parseman 0.46.0 cannot emit this: `src/table/` is an unwired prototype and
   * `package.json` has no `./table` export, so `parseman/table` does not even
   * resolve for a consumer. When it does land, a healthy artifact will import
   * `tableRules` from it — and the import-shape reasoning above has to be
   * re-derived against the emitted table before this gate can clear it. Failing
   * loudly at that moment is the point; silently passing would leave the hazard
   * uncovered under the new lowering.
   */
  const findings = artifactFallbacks(`import { tableRules } from "${TABLE_DRIVER_SPECIFIER}";\nexport const g = tableRules({ c: [] });`);
  assert.equal(findings.length, 1);
  assert.equal(findings[0].kind, 'table-lowering');
  assert.match(findings[0].detail, /table lowering has landed/);
});
