import type { Ampersand } from './ampersand.js';
import type { Any, Anonymous, Keyword } from './any.js';
import type { AtRule } from './at-rule.js';
import type { Call } from './call.js';
import type { Declaration } from './declaration.js';
import type { Dimension } from './dimension.js';
import type { Expression } from './expression.js';
import type { Operation } from './operation.js';
import type { BasicSelector } from './selector-basic.js';
import type { List } from './list.js';
import type { Mixin } from './mixin.js';
import type { Func } from './function.js';
import type { JsFunction } from './js-function.js';
import type { Ruleset } from './ruleset.js';
import type { Rules } from './rules.js';
import type { ComplexSelector } from './selector-complex.js';
import type { CompoundSelector } from './selector-compound.js';
import type { StyleImport } from './import-style.js';
import type { JsImport } from './import-js.js';
import type { Nil } from './nil.js';
import type { SelectorList } from './selector-list.js';
import type { Collection } from './collection.js';
import type { VarDeclaration } from './declaration-var.js';
import type { Rest } from './rest.js';
import type { SimpleSelector } from './selector-simple.js';
import type { PseudoSelector } from './selector-pseudo.js';
import type { Combinator } from './combinator.js';
import type { Sequence } from './sequence.js';
import type { Selector } from './selector.js';
import type { JsObject } from './js-object.js';
import type { JsArray } from './js-array.js';
import type { Num } from './number.js';
import type { Url } from './url.js';
import type { Quoted } from './quoted.js';
import type { Color } from './color.js';
import type { Reference } from './reference.js';
import type { Comment } from './comment.js';
import type { Range } from './range.js';
import type { Log } from './log.js';
import type { Paren } from './paren.js';
import type { Block } from './block.js';

export type Nodes = {
  Ampersand: typeof Ampersand;
  Any: typeof Any;
  Anonymous: typeof Anonymous;
  Keyword: typeof Keyword;
  AtRule: typeof AtRule;
  Call: typeof Call;
  Comment: typeof Comment;
  Declaration: typeof Declaration;
  Expression: typeof Expression;
  Operation: typeof Operation;
  VarDeclaration: typeof VarDeclaration;
  Dimension: typeof Dimension;
  Num: typeof Num;
  Selector: typeof Selector;
  BasicSelector: typeof BasicSelector;
  SimpleSelector: typeof SimpleSelector;
  PseudoSelector: typeof PseudoSelector;
  ComplexSelector: typeof ComplexSelector;
  CompoundSelector: typeof CompoundSelector;
  SelectorList: typeof SelectorList;
  Combinator: typeof Combinator;
  List: typeof List;
  Mixin: typeof Mixin;
  Func: typeof Func;
  JsFunction: typeof JsFunction;
  JsObject: typeof JsObject;
  JsArray: typeof JsArray;
  Ruleset: typeof Ruleset;
  Rules: typeof Rules;
  StyleImport: typeof StyleImport;
  JsImport: typeof JsImport;
  Nil: typeof Nil;
  Collection: typeof Collection;
  Rest: typeof Rest;
  Sequence: typeof Sequence;
  Url: typeof Url;
  Quoted: typeof Quoted;
  Color: typeof Color;
  Reference: typeof Reference;
  Range: typeof Range;
  Log: typeof Log;
  Paren: typeof Paren;
  Block: typeof Block;
};