/**
 * Adapted from the browser-harness cases in WPT. The CSS parser tests wrap
 * each payload in a `:nth-child(...)` selector and assert recognition rather
 * than browser CSSOM normalization.
 */
export const wptAnbParsing = {
  source: 'https://github.com/web-platform-tests/wpt/blob/a95401e4e06351eb1e15f0e15cf50abf08fa545f/css/css-syntax/anb-parsing.html',
  accepts: [
    'odd',
    'even',
    '1',
    '+1',
    '-1',
    '5n',
    '5N',
    '+n',
    'n',
    'N',
    '-n',
    '-N',
    '5n-5',
    '+n-5',
    'n-5',
    '-n-5',
    '5n +5',
    '5n -5',
    '+n +5',
    'n +5',
    '+n -5',
    '-n +5',
    '-n -5',
    '5n- 5',
    '-5n- 5',
    '+n- 5',
    'n- 5',
    '-n- 5',
    '5n + 5',
    '5n - 5',
    '+n + 5',
    'n + 5',
    '+n - 5',
    '-n + 5',
    '-n - 5'
  ],
  rejects: [
    '+ n',
    '+ n-5',
    '+ n +5',
    'n 5',
    '-n 5',
    '5n- -5',
    '5n- +5',
    '+ n- 5',
    'n- +5',
    'n- -5',
    '-n- +5',
    '-n- -5',
    '5n + +5',
    '5n + -5',
    '5n - +5',
    '5n - -5',
    '+ n + 5',
    '+n + +5',
    '+n + -5',
    '+n - +5',
    '+n - -5',
    '-n + +5',
    '-n + -5',
    '-n - +5',
    '-n - -5',
    '1 - n',
    '0 - n',
    '-1 + n',
    '2 n + 2',
    '- 2n',
    '+ 2n',
    '+2 n'
  ]
} as const;
