import { defineConfig } from 'tsdown';
import parseman from 'parseman/plugin';

/** Generated by scripts/gen-name-probes.mjs. Do not edit by hand. */
export default defineConfig([
  {
    entry: { 'probe-name-named-1': './src/probe-name-named-1.ts' },
    format: ['esm'],
    dts: false,
    outDir: './probe',
    platform: 'node',
    fixedExtension: false,
    hash: false,
    clean: false,
    deps: { onlyBundle: false },
    plugins: [parseman.rolldown()]
  },
  {
    entry: { 'probe-name-inline-1': './src/probe-name-inline-1.ts' },
    format: ['esm'],
    dts: false,
    outDir: './probe',
    platform: 'node',
    fixedExtension: false,
    hash: false,
    clean: false,
    deps: { onlyBundle: false },
    plugins: [parseman.rolldown()]
  },
  {
    entry: { 'probe-name-named-3': './src/probe-name-named-3.ts' },
    format: ['esm'],
    dts: false,
    outDir: './probe',
    platform: 'node',
    fixedExtension: false,
    hash: false,
    clean: false,
    deps: { onlyBundle: false },
    plugins: [parseman.rolldown()]
  },
  {
    entry: { 'probe-name-inline-3': './src/probe-name-inline-3.ts' },
    format: ['esm'],
    dts: false,
    outDir: './probe',
    platform: 'node',
    fixedExtension: false,
    hash: false,
    clean: false,
    deps: { onlyBundle: false },
    plugins: [parseman.rolldown()]
  }
,
  {
    entry: { 'probe-name-literal-1': './src/probe-name-literal-1.ts' },
    format: ['esm'],
    dts: false,
    outDir: './probe',
    platform: 'node',
    fixedExtension: false,
    hash: false,
    clean: false,
    deps: { onlyBundle: false },
    plugins: [parseman.rolldown()]
  }
]);
