import type { Combinator } from 'parseman';
import type { AtRuleBlock, OpaqueAtRuleBlock, ComplexSelector as AstComplexSelector, CompoundSelector as AstCompoundSelector, Color as AstColor, Declaration as AstDeclaration, Dimension as AstDimension, Interpolation, Keyword, Quoted as AstQuoted, Rule, SelectorList as AstSelectorList, SimpleSelector, ValueNode, ValueSlot, Url as AstUrl } from '@jesscss/core/ast';
type CssGrammarRuleName = 'AtPrelude' | 'AtRuleStatement' | 'AttributeSelector' | 'BasicSelector' | 'CalcCall' | 'CalcIdentOrFunction' | 'CalcParen' | 'CalcProduct' | 'CalcSum' | 'CalcValue' | 'Call' | 'Color' | 'ComplexSelector' | 'CompoundSelector' | 'ConditionalBlock' | 'ConditionalGroupAtRule' | 'ContainerPrelude' | 'ContainerQueryClause' | 'ContainerQueryPrelude' | 'CssOpaqueCaptureBody' | 'CssOpaqueCapturePrelude' | 'CssSyntax' | 'CssSyntaxAttributeModifier' | 'CssSyntaxAttributeOperator' | 'CssSyntaxConditionalAtKeyword' | 'CssSyntaxContainerAtKeyword' | 'CssSyntaxCustomProperty' | 'CssSyntaxDescriptorAtKeyword' | 'CssSyntaxDocumentAtKeyword' | 'CssSyntaxDoubleQuotedText' | 'CssSyntaxFontFeatureValueAtKeyword' | 'CssSyntaxFontFeatureValuesAtKeyword' | 'CssSyntaxGenericAtRuleName' | 'CssSyntaxImportant' | 'CssSyntaxKeyframesAtKeyword' | 'CssSyntaxKeyword' | 'CssSyntaxLayerAtKeyword' | 'CssSyntaxMalformedPseudoNumericArgument' | 'CssSyntaxMarginAtKeyword' | 'CssSyntaxMediaAtKeyword' | 'CssSyntaxNth' | 'CssSyntaxNthChildName' | 'CssSyntaxNthName' | 'CssSyntaxNthTypeName' | 'CssSyntaxOfKeyword' | 'CssSyntaxPageAtKeyword' | 'CssSyntaxProperty' | 'CssSyntaxPseudoCloseAhead' | 'CssSyntaxQueryAndOr' | 'CssSyntaxQueryComparisonOperator' | 'CssSyntaxQueryFunctionOpen' | 'CssSyntaxQueryNot' | 'CssSyntaxQueryOnly' | 'CssSyntaxScopeAtKeyword' | 'CssSyntaxSelectorArgPseudoName' | 'CssSyntaxSingleQuotedText' | 'CssSyntaxStartingStyleAtKeyword' | 'CssSyntaxStatementAtRuleName' | 'CssSyntaxSupportsAtKeyword' | 'CssSyntaxUnicodeRange' | 'CssSyntaxUrlInner' | 'CssSyntaxUrlOpen' | 'CustomProperty' | 'CustomValue' | 'Declaration' | 'DeclarationListAtRule' | 'PunctuationValue' | 'ParenValue' | 'RawParenValue' | 'DescriptorBlock' | 'Dimension' | 'DocumentBlock' | 'FeatureValueBlock' | 'FontFeatureValuesBlock' | 'GeneralEnclosed' | 'GeneralEnclosedContent' | 'GeneralEnclosedGroup' | 'GeneralEnclosedQuoted' | 'ImportStatement' | 'ImportTail' | 'ImportTailBody' | 'ImportTailRaw' | 'ImportUrl' | 'ImportUrlUnquoted' | 'Important' | 'KeyframeBlock' | 'Keyframes' | 'Keyword' | 'LayerBlock' | 'LayerStatement' | 'LeadingDashOfTypePseudoArgument' | 'LeadingDashPseudoArgument' | 'LeadingDashRawPseudoArgument' | 'MarginAtRule' | 'NestedConditionalBlock' | 'NestedLayerBlock' | 'NestedStartingStyleBlock' | 'NestingSelector' | 'OfTypePseudoArgument' | 'OpaqueAtPrelude' | 'OpaqueAtRuleBlock' | 'OpaqueBody' | 'PageBlock' | 'Percentage' | 'Property' | 'PseudoArgument' | 'PseudoSelector' | 'QueryClause' | 'QueryFeature' | 'QueryFunction' | 'QueryPrelude' | 'Quoted' | 'Ruleset' | 'ScopeBlock' | 'SelectorList' | 'StartingStyleBlock' | 'StylesheetAtRule' | 'StatementPrelude' | 'SupportsCondition' | 'SupportsInParens' | 'SupportsPrelude' | 'TopLevelComplexSelector' | 'TopLevelCompoundSelector' | 'TopLevelRuleset' | 'TopLevelSelectorList' | 'TypedNthPseudoArgument' | 'TypedOfTypePseudoArgument' | 'UnicodeRange' | 'Url' | 'Value' | 'ValueList' | 'ValueSequence' | 'TypedValue' | 'TypedValueList' | 'TypedValueSequence' | 'VarCall' | 'VarFallback' | 'VarFallbackBrace' | 'VarFallbackBracket' | 'VarFallbackCall' | 'VarFallbackEmpty' | 'VarFallbackItem' | 'VarFallbackParen' | 'VarFallbackPunctuation' | 'VarFallbackTerm' | 'keyframeSelector';
type CssGrammarSelf = {
    readonly [K in CssGrammarRuleName]: Combinator<unknown>;
};
export declare const cssFactory: (g: CssGrammarSelf) => {
    Stylesheet: Combinator<import("@jesscss/core/ast").Stylesheet>;
    SelectorList: Combinator<AstSelectorList>;
    TopLevelSelectorList: Combinator<AstSelectorList>;
    ComplexSelector: Combinator<AstComplexSelector>;
    TopLevelComplexSelector: Combinator<AstComplexSelector>;
    CompoundSelector: Combinator<AstCompoundSelector>;
    TopLevelCompoundSelector: Combinator<AstCompoundSelector>;
    BasicSelector: Combinator<SimpleSelector>;
    AttributeSelector: Combinator<SimpleSelector>;
    PseudoSelector: Combinator<import("@jesscss/core/ast").PseudoSelector | SimpleSelector>;
    PseudoArgument: Combinator<string>;
    OfTypePseudoArgument: Combinator<string>;
    LeadingDashPseudoArgument: Combinator<string>;
    TypedNthPseudoArgument: Combinator<string>;
    LeadingDashOfTypePseudoArgument: Combinator<string>;
    TypedOfTypePseudoArgument: Combinator<string>;
    LeadingDashRawPseudoArgument: Combinator<string>;
    NestingSelector: Combinator<SimpleSelector>;
    Property: Combinator<string>;
    CustomProperty: Combinator<string>;
    CustomValue: Combinator<import("@jesscss/core/ast").Any>;
    Keyword: Combinator<Keyword>;
    Color: Combinator<AstColor>;
    UnicodeRange: Combinator<import("@jesscss/core/ast").Any>;
    Percentage: Combinator<AstDimension>;
    Dimension: Combinator<AstDimension>;
    Quoted: Combinator<AstQuoted>;
    Url: Combinator<AstUrl>;
    Call: Combinator<import("@jesscss/core/ast").FunctionCall>;
    CalcCall: Combinator<import("@jesscss/core/ast").FunctionCall>;
    VarFallbackPunctuation: Combinator<import("@jesscss/core/ast").Any>;
    VarFallbackParen: Combinator<import("@jesscss/core/ast").Block>;
    VarFallbackBracket: Combinator<import("@jesscss/core/ast").Any>;
    VarFallbackBrace: Combinator<import("@jesscss/core/ast").Any>;
    VarFallbackCall: Combinator<import("@jesscss/core/ast").FunctionCall>;
    VarFallbackTerm: Combinator<ValueSlot>;
    VarFallbackEmpty: Combinator<import("@jesscss/core/ast").Any>;
    VarFallbackItem: Combinator<unknown>;
    VarFallback: Combinator<ValueSlot>;
    VarCall: Combinator<import("@jesscss/core/ast").FunctionCall>;
    CalcIdentOrFunction: Combinator<[string, import("@jesscss/core/ast").FunctionCall | Keyword | AstUrl]>;
    CalcParen: Combinator<import("@jesscss/core/ast").Block>;
    ParenValue: Combinator<import("@jesscss/core/ast").Block>;
    RawParenValue: Combinator<import("@jesscss/core/ast").Block>;
    PunctuationValue: Combinator<import("@jesscss/core/ast").Any>;
    ValueSequence: Combinator<ValueSlot>;
    ValueList: Combinator<ValueSlot>;
    CalcValue: Combinator<unknown>;
    CalcProduct: Combinator<ValueNode>;
    CalcSum: Combinator<ValueNode>;
    Value: Combinator<unknown>;
    TypedValue: Combinator<unknown>;
    TypedValueSequence: Combinator<ValueSlot>;
    TypedValueList: Combinator<ValueSlot>;
    Important: Combinator<boolean>;
    Declaration: Combinator<AstDeclaration>;
    ImportStatement: Combinator<import("@jesscss/core/ast").AtRuleStatement>;
    ImportUrl: Combinator<AstUrl>;
    ImportUrlUnquoted: Combinator<import("@jesscss/core/ast").Any>;
    ImportTailRaw: Combinator<import("@jesscss/core/ast").Any>;
    ImportTailBody: Combinator<import("@jesscss/core/ast").Any>;
    ImportTail: Combinator<import("@jesscss/core/ast").Any>;
    AtRuleStatement: Combinator<import("@jesscss/core/ast").AtRuleStatement>;
    AtPreludeWhitespace: Combinator<string>;
    AtPreludeComma: Combinator<string>;
    AtPreludeGroup: Combinator<string>;
    AtPreludeQuoted: Combinator<string>;
    AtPreludeText: Combinator<string>;
    AtRulePreludeSegments: Combinator<string>;
    LayerStatement: Combinator<import("@jesscss/core/ast").AtRuleStatement>;
    AtPrelude: Combinator<import("@jesscss/core/ast").Any | null>;
    StatementPrelude: Combinator<import("@jesscss/core/ast").Any | null>;
    OpaqueAtPrelude: Combinator<string | null>;
    OpaqueBody: Combinator<string>;
    OpaqueAtRuleBlock: Combinator<OpaqueAtRuleBlock>;
    StylesheetAtRule: Combinator<[string, AtRuleBlock | import("@jesscss/core/ast").AtRuleStatement | OpaqueAtRuleBlock]>;
    DeclarationListAtRule: Combinator<[string, AtRuleBlock | import("@jesscss/core/ast").AtRuleStatement | OpaqueAtRuleBlock]>;
    ConditionalGroupAtRule: Combinator<[string, AtRuleBlock | OpaqueAtRuleBlock]>;
    QueryBareFeature: Combinator<import("@jesscss/core/ast").Block>;
    QueryRangeFeature: Combinator<import("@jesscss/core/ast").Block>;
    QueryFeature: Combinator<import("@jesscss/core/ast").Block>;
    QueryClause: Combinator<ValueNode>;
    QueryPrelude: Combinator<ValueNode>;
    ContainerQueryClause: Combinator<ValueNode>;
    ContainerQueryPrelude: Combinator<ValueNode>;
    ContainerPrelude: Combinator<ValueNode>;
    QueryFunction: Combinator<import("@jesscss/core/ast").FunctionCall>;
    GeneralEnclosed: Combinator<import("@jesscss/core/ast").GeneralEnclosed>;
    GeneralEnclosedContent: Combinator<Interpolation>;
    GeneralEnclosedGroup: Combinator<string>;
    GeneralEnclosedQuoted: Combinator<string>;
    SupportsInParens: Combinator<ValueNode>;
    SupportsCondition: Combinator<ValueNode>;
    SupportsPrelude: Combinator<ValueNode>;
    LayerBlock: Combinator<AtRuleBlock>;
    NestedLayerBlock: Combinator<AtRuleBlock>;
    ConditionalBlock: Combinator<AtRuleBlock>;
    NestedConditionalBlock: Combinator<AtRuleBlock>;
    DescriptorBlock: Combinator<AtRuleBlock>;
    FeatureValueBlock: Combinator<AtRuleBlock>;
    FontFeatureValuesBlock: Combinator<AtRuleBlock>;
    ScopeBlock: Combinator<AtRuleBlock>;
    StartingStyleBlock: Combinator<AtRuleBlock>;
    NestedStartingStyleBlock: Combinator<AtRuleBlock>;
    DocumentBlock: Combinator<AtRuleBlock>;
    MarginAtRule: Combinator<AtRuleBlock>;
    PageBlock: Combinator<AtRuleBlock>;
    keyframeSelector: Combinator<SimpleSelector>;
    KeyframeBlock: Combinator<Rule>;
    Keyframes: Combinator<AtRuleBlock>;
    Ruleset: Combinator<Rule>;
    TopLevelRuleset: Combinator<Rule>;
    whitespace: Combinator<string[]>;
    rw: Combinator<string[]>;
};
export declare const cssGrammar: Record<string, import("parseman").FusedRule>;
export declare const cssAstGrammar: Record<string, import("parseman").FusedRule>;
export declare const cssCstGrammar: Record<string, import("parseman").FusedRule>;
export declare const Stylesheet: import("parseman").FusedRule | undefined, Ruleset: import("parseman").FusedRule | undefined, SelectorList: import("parseman").FusedRule | undefined, ComplexSelector: import("parseman").FusedRule | undefined, CompoundSelector: import("parseman").FusedRule | undefined, BasicSelector: import("parseman").FusedRule | undefined, AttributeSelector: import("parseman").FusedRule | undefined, PseudoSelector: import("parseman").FusedRule | undefined, Declaration: import("parseman").FusedRule | undefined, CustomDeclaration: import("parseman").FusedRule | undefined, Dimension: import("parseman").FusedRule | undefined, Color: import("parseman").FusedRule | undefined, Url: import("parseman").FusedRule | undefined, Call: import("parseman").FusedRule | undefined, Quoted: import("parseman").FusedRule | undefined, AtRuleStatement: import("parseman").FusedRule | undefined;
export {};
//# sourceMappingURL=grammar.d.ts.map