/**
 * Naming-cost probe: LITERAL inline bodies, no consts, 1 use(s) each.
 *
 * Generated by scripts/gen-name-probes.mjs. Do not edit by hand.
 */
import { choice, classifiedTrivia, composeLeaf, literal, many, node, optional, regex, rules, sequence } from 'parseman' with { type: 'macro' };
import type { Combinator } from 'parseman';
import { cssSyntax } from '@jesscss/parser-shared/recognition';
import { opaqueAtRuleRecognition } from '@jesscss/parser-shared/opaque-at-rule';
import { cssPseudoSyntax } from '@jesscss/parser-shared/pseudo-consts';

const blockComment = regex(/\/\*(?:[^*]|\*(?!\/))*\*\//);
const whitespaceRun = regex(/[ \t\n\r\f]+/);
const whitespace = classifiedTrivia({ whitespace: whitespaceRun, blockComment });

type Leaf = 'Identifier' | 'NumberToken' | 'HexColor' | 'DoubleQuotedText' | 'DimensionUnit';

type ProbeSelf = { readonly [K in Leaf | 'Stylesheet' | 'R0' | 'R1' | 'R2' | 'R3' | 'R4' | 'R5' | 'R6' | 'R7' | 'R8' | 'R9' | 'R10' | 'R11' | 'R12' | 'R13' | 'R14' | 'R15' | 'R16' | 'R17' | 'R18' | 'R19']: Combinator<unknown> };

const probeFactory = (g: ProbeSelf) => {
  const Stylesheet = node(
    'Stylesheet',
    many(choice(
      node('R0', sequence(
        literal('r0('),
        optional(g.Identifier),
        many(choice(g.NumberToken, g.HexColor, g.DoubleQuotedText)),
        optional(sequence(literal(','), g.DimensionUnit)),
        literal(')')
      ), () => null),
      node('R1', sequence(
        literal('r1('),
        optional(g.Identifier),
        many(choice(g.NumberToken, g.HexColor, g.DoubleQuotedText)),
        optional(sequence(literal(','), g.DimensionUnit)),
        literal(')')
      ), () => null),
      node('R2', sequence(
        literal('r2('),
        optional(g.Identifier),
        many(choice(g.NumberToken, g.HexColor, g.DoubleQuotedText)),
        optional(sequence(literal(','), g.DimensionUnit)),
        literal(')')
      ), () => null),
      node('R3', sequence(
        literal('r3('),
        optional(g.Identifier),
        many(choice(g.NumberToken, g.HexColor, g.DoubleQuotedText)),
        optional(sequence(literal(','), g.DimensionUnit)),
        literal(')')
      ), () => null),
      node('R4', sequence(
        literal('r4('),
        optional(g.Identifier),
        many(choice(g.NumberToken, g.HexColor, g.DoubleQuotedText)),
        optional(sequence(literal(','), g.DimensionUnit)),
        literal(')')
      ), () => null),
      node('R5', sequence(
        literal('r5('),
        optional(g.Identifier),
        many(choice(g.NumberToken, g.HexColor, g.DoubleQuotedText)),
        optional(sequence(literal(','), g.DimensionUnit)),
        literal(')')
      ), () => null),
      node('R6', sequence(
        literal('r6('),
        optional(g.Identifier),
        many(choice(g.NumberToken, g.HexColor, g.DoubleQuotedText)),
        optional(sequence(literal(','), g.DimensionUnit)),
        literal(')')
      ), () => null),
      node('R7', sequence(
        literal('r7('),
        optional(g.Identifier),
        many(choice(g.NumberToken, g.HexColor, g.DoubleQuotedText)),
        optional(sequence(literal(','), g.DimensionUnit)),
        literal(')')
      ), () => null),
      node('R8', sequence(
        literal('r8('),
        optional(g.Identifier),
        many(choice(g.NumberToken, g.HexColor, g.DoubleQuotedText)),
        optional(sequence(literal(','), g.DimensionUnit)),
        literal(')')
      ), () => null),
      node('R9', sequence(
        literal('r9('),
        optional(g.Identifier),
        many(choice(g.NumberToken, g.HexColor, g.DoubleQuotedText)),
        optional(sequence(literal(','), g.DimensionUnit)),
        literal(')')
      ), () => null),
      node('R10', sequence(
        literal('r10('),
        optional(g.Identifier),
        many(choice(g.NumberToken, g.HexColor, g.DoubleQuotedText)),
        optional(sequence(literal(','), g.DimensionUnit)),
        literal(')')
      ), () => null),
      node('R11', sequence(
        literal('r11('),
        optional(g.Identifier),
        many(choice(g.NumberToken, g.HexColor, g.DoubleQuotedText)),
        optional(sequence(literal(','), g.DimensionUnit)),
        literal(')')
      ), () => null),
      node('R12', sequence(
        literal('r12('),
        optional(g.Identifier),
        many(choice(g.NumberToken, g.HexColor, g.DoubleQuotedText)),
        optional(sequence(literal(','), g.DimensionUnit)),
        literal(')')
      ), () => null),
      node('R13', sequence(
        literal('r13('),
        optional(g.Identifier),
        many(choice(g.NumberToken, g.HexColor, g.DoubleQuotedText)),
        optional(sequence(literal(','), g.DimensionUnit)),
        literal(')')
      ), () => null),
      node('R14', sequence(
        literal('r14('),
        optional(g.Identifier),
        many(choice(g.NumberToken, g.HexColor, g.DoubleQuotedText)),
        optional(sequence(literal(','), g.DimensionUnit)),
        literal(')')
      ), () => null),
      node('R15', sequence(
        literal('r15('),
        optional(g.Identifier),
        many(choice(g.NumberToken, g.HexColor, g.DoubleQuotedText)),
        optional(sequence(literal(','), g.DimensionUnit)),
        literal(')')
      ), () => null),
      node('R16', sequence(
        literal('r16('),
        optional(g.Identifier),
        many(choice(g.NumberToken, g.HexColor, g.DoubleQuotedText)),
        optional(sequence(literal(','), g.DimensionUnit)),
        literal(')')
      ), () => null),
      node('R17', sequence(
        literal('r17('),
        optional(g.Identifier),
        many(choice(g.NumberToken, g.HexColor, g.DoubleQuotedText)),
        optional(sequence(literal(','), g.DimensionUnit)),
        literal(')')
      ), () => null),
      node('R18', sequence(
        literal('r18('),
        optional(g.Identifier),
        many(choice(g.NumberToken, g.HexColor, g.DoubleQuotedText)),
        optional(sequence(literal(','), g.DimensionUnit)),
        literal(')')
      ), () => null),
      node('R19', sequence(
        literal('r19('),
        optional(g.Identifier),
        many(choice(g.NumberToken, g.HexColor, g.DoubleQuotedText)),
        optional(sequence(literal(','), g.DimensionUnit)),
        literal(')')
      ), () => null)
    )),
    () => null
  );

  return { Stylesheet };
};

export const probe = composeLeaf([cssSyntax, opaqueAtRuleRecognition, cssPseudoSyntax, rules(
  { trivia: whitespace },
  probeFactory
)]);
