/**
 * Naming-cost probe: NAMED sub-productions, 1 use(s) each.
 *
 * Generated by scripts/gen-name-probes.mjs. Do not edit by hand.
 */
import { choice, classifiedTrivia, composeLeaf, literal, many, node, optional, regex, rules, sequence } from 'parseman' with { type: 'macro' };
import type { Combinator } from 'parseman';
import { cssSyntax } from '@jesscss/parser-shared/recognition';
import { opaqueAtRuleRecognition } from '@jesscss/parser-shared/opaque-at-rule';
import { cssPseudoSyntax } from '@jesscss/parser-shared/pseudo-consts';

const blockComment = regex(/\/\*(?:[^*]|\*(?!\/))*\*\//);
const whitespaceRun = regex(/[ \t\n\r\f]+/);
const whitespace = classifiedTrivia({ whitespace: whitespaceRun, blockComment });

type Leaf = 'Identifier' | 'NumberToken' | 'HexColor' | 'DoubleQuotedText' | 'DimensionUnit';

type ProbeSelf = { readonly [K in Leaf | 'Stylesheet' | 'R0' | 'R1' | 'R2' | 'R3' | 'R4' | 'R5' | 'R6' | 'R7' | 'R8' | 'R9' | 'R10' | 'R11' | 'R12' | 'R13' | 'R14' | 'R15' | 'R16' | 'R17' | 'R18' | 'R19']: Combinator<unknown> };

const probeFactory = (g: ProbeSelf) => {
  const R0 = node(
    'R0',
    sequence(
      literal('r0('),
      optional(g.Identifier),
      many(choice(g.NumberToken, g.HexColor, g.DoubleQuotedText)),
      optional(sequence(literal(','), g.DimensionUnit)),
      literal(')')
    ),
    () => null
  );

  const R1 = node(
    'R1',
    sequence(
      literal('r1('),
      optional(g.Identifier),
      many(choice(g.NumberToken, g.HexColor, g.DoubleQuotedText)),
      optional(sequence(literal(','), g.DimensionUnit)),
      literal(')')
    ),
    () => null
  );

  const R2 = node(
    'R2',
    sequence(
      literal('r2('),
      optional(g.Identifier),
      many(choice(g.NumberToken, g.HexColor, g.DoubleQuotedText)),
      optional(sequence(literal(','), g.DimensionUnit)),
      literal(')')
    ),
    () => null
  );

  const R3 = node(
    'R3',
    sequence(
      literal('r3('),
      optional(g.Identifier),
      many(choice(g.NumberToken, g.HexColor, g.DoubleQuotedText)),
      optional(sequence(literal(','), g.DimensionUnit)),
      literal(')')
    ),
    () => null
  );

  const R4 = node(
    'R4',
    sequence(
      literal('r4('),
      optional(g.Identifier),
      many(choice(g.NumberToken, g.HexColor, g.DoubleQuotedText)),
      optional(sequence(literal(','), g.DimensionUnit)),
      literal(')')
    ),
    () => null
  );

  const R5 = node(
    'R5',
    sequence(
      literal('r5('),
      optional(g.Identifier),
      many(choice(g.NumberToken, g.HexColor, g.DoubleQuotedText)),
      optional(sequence(literal(','), g.DimensionUnit)),
      literal(')')
    ),
    () => null
  );

  const R6 = node(
    'R6',
    sequence(
      literal('r6('),
      optional(g.Identifier),
      many(choice(g.NumberToken, g.HexColor, g.DoubleQuotedText)),
      optional(sequence(literal(','), g.DimensionUnit)),
      literal(')')
    ),
    () => null
  );

  const R7 = node(
    'R7',
    sequence(
      literal('r7('),
      optional(g.Identifier),
      many(choice(g.NumberToken, g.HexColor, g.DoubleQuotedText)),
      optional(sequence(literal(','), g.DimensionUnit)),
      literal(')')
    ),
    () => null
  );

  const R8 = node(
    'R8',
    sequence(
      literal('r8('),
      optional(g.Identifier),
      many(choice(g.NumberToken, g.HexColor, g.DoubleQuotedText)),
      optional(sequence(literal(','), g.DimensionUnit)),
      literal(')')
    ),
    () => null
  );

  const R9 = node(
    'R9',
    sequence(
      literal('r9('),
      optional(g.Identifier),
      many(choice(g.NumberToken, g.HexColor, g.DoubleQuotedText)),
      optional(sequence(literal(','), g.DimensionUnit)),
      literal(')')
    ),
    () => null
  );

  const R10 = node(
    'R10',
    sequence(
      literal('r10('),
      optional(g.Identifier),
      many(choice(g.NumberToken, g.HexColor, g.DoubleQuotedText)),
      optional(sequence(literal(','), g.DimensionUnit)),
      literal(')')
    ),
    () => null
  );

  const R11 = node(
    'R11',
    sequence(
      literal('r11('),
      optional(g.Identifier),
      many(choice(g.NumberToken, g.HexColor, g.DoubleQuotedText)),
      optional(sequence(literal(','), g.DimensionUnit)),
      literal(')')
    ),
    () => null
  );

  const R12 = node(
    'R12',
    sequence(
      literal('r12('),
      optional(g.Identifier),
      many(choice(g.NumberToken, g.HexColor, g.DoubleQuotedText)),
      optional(sequence(literal(','), g.DimensionUnit)),
      literal(')')
    ),
    () => null
  );

  const R13 = node(
    'R13',
    sequence(
      literal('r13('),
      optional(g.Identifier),
      many(choice(g.NumberToken, g.HexColor, g.DoubleQuotedText)),
      optional(sequence(literal(','), g.DimensionUnit)),
      literal(')')
    ),
    () => null
  );

  const R14 = node(
    'R14',
    sequence(
      literal('r14('),
      optional(g.Identifier),
      many(choice(g.NumberToken, g.HexColor, g.DoubleQuotedText)),
      optional(sequence(literal(','), g.DimensionUnit)),
      literal(')')
    ),
    () => null
  );

  const R15 = node(
    'R15',
    sequence(
      literal('r15('),
      optional(g.Identifier),
      many(choice(g.NumberToken, g.HexColor, g.DoubleQuotedText)),
      optional(sequence(literal(','), g.DimensionUnit)),
      literal(')')
    ),
    () => null
  );

  const R16 = node(
    'R16',
    sequence(
      literal('r16('),
      optional(g.Identifier),
      many(choice(g.NumberToken, g.HexColor, g.DoubleQuotedText)),
      optional(sequence(literal(','), g.DimensionUnit)),
      literal(')')
    ),
    () => null
  );

  const R17 = node(
    'R17',
    sequence(
      literal('r17('),
      optional(g.Identifier),
      many(choice(g.NumberToken, g.HexColor, g.DoubleQuotedText)),
      optional(sequence(literal(','), g.DimensionUnit)),
      literal(')')
    ),
    () => null
  );

  const R18 = node(
    'R18',
    sequence(
      literal('r18('),
      optional(g.Identifier),
      many(choice(g.NumberToken, g.HexColor, g.DoubleQuotedText)),
      optional(sequence(literal(','), g.DimensionUnit)),
      literal(')')
    ),
    () => null
  );

  const R19 = node(
    'R19',
    sequence(
      literal('r19('),
      optional(g.Identifier),
      many(choice(g.NumberToken, g.HexColor, g.DoubleQuotedText)),
      optional(sequence(literal(','), g.DimensionUnit)),
      literal(')')
    ),
    () => null
  );

  const Stylesheet = node(
    'Stylesheet',
    many(choice(
      g.R0,
      g.R1,
      g.R2,
      g.R3,
      g.R4,
      g.R5,
      g.R6,
      g.R7,
      g.R8,
      g.R9,
      g.R10,
      g.R11,
      g.R12,
      g.R13,
      g.R14,
      g.R15,
      g.R16,
      g.R17,
      g.R18,
      g.R19
    )),
    () => null
  );

  return { Stylesheet, R0, R1, R2, R3, R4, R5, R6, R7, R8, R9, R10, R11, R12, R13, R14, R15, R16, R17, R18, R19 };
};

export const probe = composeLeaf([cssSyntax, opaqueAtRuleRecognition, cssPseudoSyntax, rules(
  { trivia: whitespace },
  probeFactory
)]);
