import { LINT_CODES } from './tolerant-cst.js';

export const LINT_RULE_NAMES = {
  emptyRules: 'block-no-empty',
  unknownProperties: 'property-no-unknown',
  deprecatedProperties: 'property-no-deprecated',
  unknownPropertyValues: 'declaration-property-value-no-unknown',
  unknownAtRules: 'at-rule-no-unknown',
  unknownAtRuleDescriptors: 'at-rule-descriptor-no-unknown',
  unknownAtRuleDescriptorValues: 'at-rule-descriptor-value-no-unknown',
  duplicateProperties: 'declaration-block-no-duplicate-properties',
  shorthandPropertyOverrides: 'declaration-block-no-shorthand-property-overrides',
  duplicateCustomProperties: 'declaration-block-no-duplicate-custom-properties',
  hexColorLength: 'color-no-invalid-hex',
  zeroUnits: 'length-zero-no-unit',
  customPropertyMissingVarFunction: 'custom-property-no-missing-var-function',
  unknownCustomProperties: 'no-unknown-custom-properties',
  keyframeDuplicateSelectors: 'keyframe-block-no-duplicate-selectors',
  keyframeDeclarationNoImportant: 'keyframe-declaration-no-important',
  declarationNoImportant: 'declaration-no-important',
  invalidNamedGridAreas: 'named-grid-areas-no-invalid',
  fontFamilyDuplicateNames: 'font-family-no-duplicate-names',
  fontFamilyMissingGeneric: 'font-family-no-missing-generic-family-keyword',
  fontFaceMissingRequiredProperties: 'font-face-no-missing-required-properties',
  propertyIgnoredDueToDisplay: 'property-ignored-due-to-display',
  boxModel: 'box-model',
  float: 'float',
  propertyNoVendorPrefix: 'property-no-vendor-prefix',
  atRuleNoVendorPrefix: 'at-rule-no-vendor-prefix',
  valueNoVendorPrefix: 'value-no-vendor-prefix',
  vendorPrefix: 'vendor-prefix',
  compatibleVendorPrefixes: 'compatible-vendor-prefixes',
  unknownVendorSpecificProperties: 'unknown-vendor-specific-properties',
  ieHack: 'ie-hack',
  importStatement: 'import-statement',
  invalidImportPosition: 'no-invalid-position-at-import-rule',
  duplicateAtImportRules: 'no-duplicate-at-import-rules',
  unknownAnimations: 'no-unknown-animations',
  duplicateSelectors: 'no-duplicate-selectors',
  unknownUnits: 'unit-no-unknown',
  unknownFunctions: 'function-no-unknown',
  linearGradientNonstandardDirection: 'function-linear-gradient-no-nonstandard-direction',
  colorFunctionNotation: 'color-function-notation',
  alphaValueNotation: 'alpha-value-notation',
  hueDegreeNotation: 'hue-degree-notation',
  unknownMediaFeatureNames: 'media-feature-name-no-unknown',
  mediaFeatureNameNoVendorPrefix: 'media-feature-name-no-vendor-prefix',
  unknownMediaFeatureValues: 'media-feature-name-value-no-unknown',
  unknownPseudoClasses: 'selector-pseudo-class-no-unknown',
  unknownPseudoElements: 'selector-pseudo-element-no-unknown',
  selectorNoVendorPrefix: 'selector-no-vendor-prefix',
  selectorClassPattern: 'selector-class-pattern',
  customPropertyPattern: 'custom-property-pattern',
  keyframesNamePattern: 'keyframes-name-pattern',
  unmatchableAnbSelectors: 'selector-anb-no-unmatchable',
  unknownTypeSelectors: 'selector-type-no-unknown',
  selectorMaxId: 'selector-max-id',
  selectorMaxUniversal: 'selector-max-universal',
  selectorMaxSpecificity: 'selector-max-specificity',
  noDescendingSpecificity: 'no-descending-specificity',
  incompatibleMathFunctionUnits: 'jess/no-incompatible-math-function-units',
  invalidColorFunctionChannels: 'color-function-no-invalid-arguments',
  invalidTypedCustomPropertyRegistration: 'jess/no-invalid-typed-custom-property-registration',
  invalidTypedCustomPropertyValue: 'jess/no-invalid-typed-custom-property-value',
  shadowedTokens: 'jess/no-shadowed-token',
  unusedVariables: 'jess/no-unused-variable',
  unusedMixins: 'jess/no-unused-mixin',
  unusedFunctions: 'jess/no-unused-function',
  impossibleGuards: 'jess/no-impossible-guard',
  unusedDefaultBranches: 'jess/no-unused-default-branch',
  duplicateModuleLoads: 'jess/no-duplicate-module-load',
  unboundedExtends: 'jess/no-unbounded-extend',
  deadExtends: 'jess/no-dead-extend',
  suspiciousMapKeyAccess: 'jess/no-suspicious-map-key-access',
  unsupportedSassForm: 'jess/unsupported-sass-form'
} as const;

export type LintRuleName = typeof LINT_RULE_NAMES[keyof typeof LINT_RULE_NAMES];

const DIAGNOSTIC_BY_RULE: Record<LintRuleName, string> = {
  [LINT_RULE_NAMES.emptyRules]: LINT_CODES.emptyRules,
  [LINT_RULE_NAMES.unknownProperties]: LINT_CODES.unknownProperties,
  [LINT_RULE_NAMES.deprecatedProperties]: LINT_CODES.deprecatedProperties,
  [LINT_RULE_NAMES.unknownPropertyValues]: LINT_CODES.unknownPropertyValues,
  [LINT_RULE_NAMES.unknownAtRules]: LINT_CODES.unknownAtRules,
  [LINT_RULE_NAMES.unknownAtRuleDescriptors]: LINT_CODES.unknownAtRuleDescriptors,
  [LINT_RULE_NAMES.unknownAtRuleDescriptorValues]: LINT_CODES.unknownAtRuleDescriptorValues,
  [LINT_RULE_NAMES.duplicateProperties]: LINT_CODES.duplicateProperties,
  [LINT_RULE_NAMES.shorthandPropertyOverrides]: LINT_CODES.shorthandPropertyOverrides,
  [LINT_RULE_NAMES.duplicateCustomProperties]: LINT_CODES.duplicateCustomProperties,
  [LINT_RULE_NAMES.hexColorLength]: LINT_CODES.hexColorLength,
  [LINT_RULE_NAMES.zeroUnits]: LINT_CODES.zeroUnits,
  [LINT_RULE_NAMES.customPropertyMissingVarFunction]: LINT_CODES.customPropertyMissingVarFunction,
  [LINT_RULE_NAMES.unknownCustomProperties]: LINT_CODES.unknownCustomProperties,
  [LINT_RULE_NAMES.keyframeDuplicateSelectors]: LINT_CODES.keyframeDuplicateSelectors,
  [LINT_RULE_NAMES.keyframeDeclarationNoImportant]: LINT_CODES.keyframeDeclarationNoImportant,
  [LINT_RULE_NAMES.declarationNoImportant]: LINT_CODES.declarationNoImportant,
  [LINT_RULE_NAMES.invalidNamedGridAreas]: LINT_CODES.invalidNamedGridAreas,
  [LINT_RULE_NAMES.fontFamilyDuplicateNames]: LINT_CODES.fontFamilyDuplicateNames,
  [LINT_RULE_NAMES.fontFamilyMissingGeneric]: LINT_CODES.fontFamilyMissingGeneric,
  [LINT_RULE_NAMES.fontFaceMissingRequiredProperties]: LINT_CODES.fontFaceMissingRequiredProperties,
  [LINT_RULE_NAMES.propertyIgnoredDueToDisplay]: LINT_CODES.propertyIgnoredDueToDisplay,
  [LINT_RULE_NAMES.boxModel]: LINT_CODES.boxModel,
  [LINT_RULE_NAMES.float]: LINT_CODES.float,
  [LINT_RULE_NAMES.propertyNoVendorPrefix]: LINT_CODES.propertyNoVendorPrefix,
  [LINT_RULE_NAMES.atRuleNoVendorPrefix]: LINT_CODES.atRuleNoVendorPrefix,
  [LINT_RULE_NAMES.valueNoVendorPrefix]: LINT_CODES.valueNoVendorPrefix,
  [LINT_RULE_NAMES.vendorPrefix]: LINT_CODES.vendorPrefix,
  [LINT_RULE_NAMES.compatibleVendorPrefixes]: LINT_CODES.compatibleVendorPrefixes,
  [LINT_RULE_NAMES.unknownVendorSpecificProperties]: LINT_CODES.unknownVendorSpecificProperties,
  [LINT_RULE_NAMES.ieHack]: LINT_CODES.ieHack,
  [LINT_RULE_NAMES.importStatement]: LINT_CODES.importStatement,
  [LINT_RULE_NAMES.invalidImportPosition]: LINT_CODES.invalidImportPosition,
  [LINT_RULE_NAMES.duplicateAtImportRules]: LINT_CODES.duplicateAtImportRules,
  [LINT_RULE_NAMES.unknownAnimations]: LINT_CODES.unknownAnimations,
  [LINT_RULE_NAMES.duplicateSelectors]: LINT_CODES.duplicateSelectors,
  [LINT_RULE_NAMES.unknownUnits]: LINT_CODES.unknownUnits,
  [LINT_RULE_NAMES.unknownFunctions]: LINT_CODES.unknownFunctions,
  [LINT_RULE_NAMES.linearGradientNonstandardDirection]: LINT_CODES.linearGradientNonstandardDirection,
  [LINT_RULE_NAMES.colorFunctionNotation]: LINT_CODES.colorFunctionNotation,
  [LINT_RULE_NAMES.alphaValueNotation]: LINT_CODES.alphaValueNotation,
  [LINT_RULE_NAMES.hueDegreeNotation]: LINT_CODES.hueDegreeNotation,
  [LINT_RULE_NAMES.unknownMediaFeatureNames]: LINT_CODES.unknownMediaFeatureNames,
  [LINT_RULE_NAMES.mediaFeatureNameNoVendorPrefix]: LINT_CODES.mediaFeatureNameNoVendorPrefix,
  [LINT_RULE_NAMES.unknownMediaFeatureValues]: LINT_CODES.unknownMediaFeatureValues,
  [LINT_RULE_NAMES.unknownPseudoClasses]: LINT_CODES.unknownPseudoClasses,
  [LINT_RULE_NAMES.unknownPseudoElements]: LINT_CODES.unknownPseudoElements,
  [LINT_RULE_NAMES.selectorNoVendorPrefix]: LINT_CODES.selectorNoVendorPrefix,
  [LINT_RULE_NAMES.selectorClassPattern]: LINT_CODES.selectorClassPattern,
  [LINT_RULE_NAMES.customPropertyPattern]: LINT_CODES.customPropertyPattern,
  [LINT_RULE_NAMES.keyframesNamePattern]: LINT_CODES.keyframesNamePattern,
  [LINT_RULE_NAMES.unmatchableAnbSelectors]: LINT_CODES.unmatchableAnbSelectors,
  [LINT_RULE_NAMES.unknownTypeSelectors]: LINT_CODES.unknownTypeSelectors,
  [LINT_RULE_NAMES.selectorMaxId]: LINT_CODES.selectorMaxId,
  [LINT_RULE_NAMES.selectorMaxUniversal]: LINT_CODES.selectorMaxUniversal,
  [LINT_RULE_NAMES.selectorMaxSpecificity]: LINT_CODES.selectorMaxSpecificity,
  [LINT_RULE_NAMES.noDescendingSpecificity]: LINT_CODES.noDescendingSpecificity,
  [LINT_RULE_NAMES.incompatibleMathFunctionUnits]: LINT_CODES.incompatibleMathFunctionUnits,
  [LINT_RULE_NAMES.invalidColorFunctionChannels]: LINT_CODES.invalidColorFunctionChannels,
  [LINT_RULE_NAMES.invalidTypedCustomPropertyRegistration]: LINT_CODES.invalidTypedCustomPropertyRegistration,
  [LINT_RULE_NAMES.invalidTypedCustomPropertyValue]: LINT_CODES.invalidTypedCustomPropertyValue,
  [LINT_RULE_NAMES.shadowedTokens]: LINT_CODES.shadowedTokens,
  [LINT_RULE_NAMES.unusedVariables]: LINT_CODES.unusedVariables,
  [LINT_RULE_NAMES.unusedMixins]: LINT_CODES.unusedMixins,
  [LINT_RULE_NAMES.unusedFunctions]: LINT_CODES.unusedFunctions,
  [LINT_RULE_NAMES.impossibleGuards]: LINT_CODES.impossibleGuards,
  [LINT_RULE_NAMES.unusedDefaultBranches]: LINT_CODES.unusedDefaultBranches,
  [LINT_RULE_NAMES.duplicateModuleLoads]: LINT_CODES.duplicateModuleLoads,
  [LINT_RULE_NAMES.unboundedExtends]: LINT_CODES.unboundedExtends,
  [LINT_RULE_NAMES.deadExtends]: LINT_CODES.deadExtends,
  [LINT_RULE_NAMES.suspiciousMapKeyAccess]: LINT_CODES.suspiciousMapKeyAccess,
  [LINT_RULE_NAMES.unsupportedSassForm]: LINT_CODES.unsupportedSassForm
};

const RULE_BY_DIAGNOSTIC: Record<string, string> = Object.fromEntries(
  Object.entries(DIAGNOSTIC_BY_RULE).map(([ruleName, diagnosticCode]) => [diagnosticCode, ruleName])
);

function isLintRuleName(ruleName: string): ruleName is LintRuleName {
  return Object.hasOwn(DIAGNOSTIC_BY_RULE, ruleName);
}

export function diagnosticCodeForRuleName(ruleName: string): string | undefined {
  return isLintRuleName(ruleName) ? DIAGNOSTIC_BY_RULE[ruleName] : undefined;
}

export function ruleNameForDiagnosticCode(code: string): string {
  return RULE_BY_DIAGNOSTIC[code] ?? code;
}
